/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '32': '32px',
        '40': '40px',
      },
      colors: {
        primary: "#1e3a8a",
        "primary-deep": "#0f2360",
        "primary-light": "#6b8aff",
        "primary-container": "#1e3a8a",
        "on-primary": "#ffffff",
        "on-primary-container": "#b6c4ff",
        "primary-fixed": "#e8edff",
        "primary-fixed-dim": "#c5d0ff",
        "on-primary-fixed": "#00144c",
        "on-primary-fixed-variant": "#264191",
        secondary: "#fd761a",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffc329",
        "on-secondary-container": "#6f5100",
        "secondary-fixed": "#ffdf9f",
        "secondary-fixed-dim": "#f9bd22",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5c4300",
        tertiary: "#f7be1d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4e05b7",
        "on-tertiary-container": "#b89cff",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#5417be",
        surface: "#f8f9fc",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#444651",
        "surface-variant": "#dae2fd",
        background: "#f8f9fc",
        "on-background": "#131b2e",
        outline: "#757682",
        "outline-variant": "#c5c5d3",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#b6c4ff",
        "surface-tint": "#4059aa",
        "accent-deep": "#f59e0b",
        "text-muted": "#64748b",
        "bg-off-white": "#f5f6fa",
        whatsapp: "#25D366",
        success: "#16a34a",
        "success-foreground": "#ffffff",
      },
      fontFamily: {
        display: ['"Tajawal"', '"Cairo"', '"Poppins"', 'system-ui', 'sans-serif'],
        sans: ['"Tajawal"', '"Cairo"', '"Poppins"', 'system-ui', 'sans-serif'],
        "headline-lg": ['"Cairo"', 'sans-serif'],
        "body-md": ['"Cairo"', 'sans-serif'],
        "body-lg": ['"Cairo"', 'sans-serif'],
        "headline-xl": ['"Cairo"', 'sans-serif'],
        "label-sm": ['"Tajawal"', 'sans-serif'],
        "display-lg": ['"Cairo"', 'sans-serif'],
        "display-lg-mobile": ['"Cairo"', 'sans-serif'],
        "label-md": ['"Tajawal"', 'sans-serif'],
        poppins: ['"Poppins"', 'sans-serif'],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.75", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.75", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", fontWeight: "800" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
        "icon-hero": "300px",
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "16px",
        gutter: "16px",
        '280': '280px',
        '400': '400px',
        '618': '618px',
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        card: "0 8px 30px -10px rgba(30, 58, 138, 0.16)",
        "card-hover": "0 18px 35px -12px rgba(30, 58, 138, 0.28)",
        "card-sm": "0 8px 30px -10px rgba(30, 58, 138, 0.1)",
        highlight: "0 0 30px rgba(247, 190, 29, 0.55)",
        elegant: "0 24px 60px -24px rgba(30, 58, 138, 0.38)",
        neon: "0 0 30px rgba(107, 138, 255, 0.55)",
        gold: "0 10px 35px -10px rgba(247, 190, 29, 0.5)",
      },
      width: {
        drawer: '280px',
      },
      minHeight: {
        '400': '400px',
        '618': '618px',
      },
      flex: {
        '1.5': '1.5',
      },
      zIndex: {
        '60': '60',
        '70': '70',
      },
      keyframes: {
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(30, 58, 138, 0.3)' },
          '50%': { boxShadow: '0 0 50px rgba(107, 138, 255, 0.6)' },
        },
        'float-slow': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '50%': { transform: 'translate(20px, -20px) scale(1.05)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(18px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'bounce-soft': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        'pulse-slow': 'pulse-slow 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        'spin-slow': 'spin 60s linear infinite',
        'float-slow': 'float-slow 9s ease-in-out infinite',
        'fade-up': 'fade-up 0.7s cubic-bezier(0.2, 0.8, 0.2, 1) both',
        'fade-in': 'fade-in 0.5s ease-out both',
        'scale-in': 'scale-in 0.35s cubic-bezier(0.2, 0.8, 0.2, 1) both',
        'bounce-soft': 'bounce-soft 2.5s ease-in-out infinite',
        marquee: 'marquee 30s linear infinite',
      },
    },
  },
  plugins: [],
}
