/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '32': '32px',
        '40': '40px',
      },
      colors: {
        primary: "#4169e1",
        "primary-deep": "#1a3fa0",
        "primary-light": "#6b8aff",
        "primary-container": "#1e3a8a",
        "on-primary": "#ffffff",
        "on-primary-container": "#b6c4ff",
        "primary-fixed": "#e8edff",
        "primary-fixed-dim": "#c5d0ff",
        "on-primary-fixed": "#00144c",
        "on-primary-fixed-variant": "#264191",
        secondary: "#795900",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffc329",
        "on-secondary-container": "#6f5100",
        "secondary-fixed": "#ffdf9f",
        "secondary-fixed-dim": "#f9bd22",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5c4300",
        tertiary: "#340082",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4e05b7",
        "on-tertiary-container": "#b89cff",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#5417be",
        surface: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#444651",
        "surface-variant": "#dae2fd",
        background: "#faf8ff",
        "on-background": "#131b2e",
        outline: "#757682",
        "outline-variant": "#c5c5d3",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#b6c4ff",
        "surface-tint": "#4059aa",
        "accent-deep": "#f59e0b",
        "text-muted": "#64748b",
        "bg-off-white": "#f8fafc",
        "whatsapp": "#25D366",
      },
      fontFamily: {
        "headline-lg": ["Cairo", "sans-serif"],
        "body-md": ["Cairo", "sans-serif"],
        "body-lg": ["Cairo", "sans-serif"],
        "headline-xl": ["Cairo", "sans-serif"],
        "label-sm": ["Tajawal", "sans-serif"],
        "display-lg": ["Cairo", "sans-serif"],
        "display-lg-mobile": ["Cairo", "sans-serif"],
        "label-md": ["Tajawal", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", fontWeight: "800" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-sm": ["8px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" }],
        "icon-hero": "300px",
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        gutter: "24px",
        '280': '280px',
        '400': '400px',
        '618': '618px',
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        card: "0 12px 30px rgba(65, 105, 225, 0.12)",
        "card-hover": "0 20px 40px rgba(65, 105, 225, 0.18)",
        "card-sm": "0 12px 30px rgba(65, 105, 225, 0.08)",
        'highlight': '0 0 20px rgba(255, 195, 41, 0.5)',
      },
      width: {
        'drawer': '280px',
      },
      minHeight: {
        '400': '400px',
        '618': '618px',
      },
      flex: {
        '1.5': '1.5',
      },
      zIndex: {
        '60': '60',
        '70': '70',
      },
      keyframes: {
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
      animation: {
        'pulse-slow': 'pulse-slow 6s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
      },
    },
  },
  plugins: [],
}
