/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Dynamic track card colors
    'bg-emerald-50', 'border-emerald-200', 'text-emerald-700', 'text-emerald-600', 'text-emerald-500', 'border-emerald-50', 'bg-emerald',
    'bg-blue-50', 'border-blue-200', 'text-blue-700', 'text-blue-600', 'text-blue-500', 'border-blue-50', 'bg-blue',
    'bg-purple-50', 'border-purple-200', 'text-purple-700', 'text-purple-600', 'text-purple-500', 'border-purple-50', 'bg-purple',
    'from-emerald-400', 'via-teal-400', 'to-cyan-400',
    'from-blue-500', 'via-indigo-500', 'to-violet-500',
    'from-purple-500', 'via-fuchsia-500', 'to-pink-500',
    'from-emerald-500', 'to-teal-500',
    'from-blue-500', 'to-indigo-500',
    'from-purple-500', 'to-fuchsia-500',
    'shadow-emerald-200', 'shadow-blue-200', 'shadow-purple-200',
  ],
  theme: {
    extend: {
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '20': '20px',
        '24': '24px',
        '32': '32px',
        'full': '9999px',
      },
      colors: {
        primary: "var(--color-primary)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-active": "var(--color-primary-active)",
        "primary-light": "var(--color-primary-light)",
        "primary-muted": "var(--color-primary-muted)",
        "primary-container": "var(--color-primary-container)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-light": "var(--color-accent-light)",
        "on-accent": "#ffffff",
        "accent-container": "var(--color-accent-container)",
        "accent-border": "var(--color-accent-border)",
        "accent-text": "var(--color-accent-text)",
        exclusive: "var(--color-exclusive)",
        "exclusive-hover": "var(--color-exclusive-hover)",
        "exclusive-bg": "var(--color-exclusive-bg)",
        "exclusive-border": "var(--color-exclusive-border)",
        "exclusive-text": "var(--color-exclusive-text)",
        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        surface: "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-hover": "var(--color-surface-hover)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-variant": "var(--color-surface-variant)",
        background: "var(--color-bg)",
        "bg-secondary": "var(--color-bg-secondary)",
        "bg-tertiary": "var(--color-bg-tertiary)",
        "on-background": "var(--color-on-background)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "border-subtle": "var(--color-border-subtle)",
        "border-strong": "var(--color-border-strong)",
        error: "var(--color-danger)",
        "on-error": "#ffffff",
        "error-container": "var(--color-danger-light)",
        "on-error-container": "var(--color-danger)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        success: "var(--color-success)",
        "success-bg": "var(--color-success-light)",
        "warning": "var(--color-warning)",
        "warning-bg": "var(--color-warning-light)",
        "danger": "var(--color-danger)",
        "danger-bg": "var(--color-danger-light)",
        "info": "var(--color-info)",
        "info-bg": "var(--color-info-light)",
        whatsapp: "#25D366",
        glass: {
          light: "rgba(255, 255, 255, 0.9)",
          dark: "rgba(255, 255, 255, 0.05)",
        },
      },
      fontFamily: {
        display: ['var(--font-tajawal)', 'Tajawal', 'system-ui', 'sans-serif'],
        sans: ['var(--font-cairo)', 'Cairo', 'system-ui', 'sans-serif'],
        "headline-xl": ['var(--font-tajawal)', 'Tajawal', 'sans-serif'],
        "headline-lg": ['var(--font-tajawal)', 'Tajawal', 'sans-serif'],
        "headline-md": ['var(--font-tajawal)', 'Tajawal', 'sans-serif'],
        "headline-lg-mobile": ['var(--font-tajawal)', 'Tajawal', 'sans-serif'],
        "body-lg": ['var(--font-cairo)', 'Cairo', 'sans-serif'],
        "body-md": ['var(--font-cairo)', 'Cairo', 'sans-serif'],
        "body-sm": ['var(--font-cairo)', 'Cairo', 'sans-serif'],
        "label-md": ['var(--font-cairo)', 'Cairo', 'sans-serif'],
        "label-sm": ['var(--font-cairo)', 'Cairo', 'sans-serif'],
      },
      fontSize: {
        "xs": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "base": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "xl": ["20px", { lineHeight: "1.5", fontWeight: "500" }],
        "2xl": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
      },
      spacing: {
        "xs": "4px",
        "sm": "12px",
        "base": "8px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "2xl": "80px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack": "8px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        "soft": "0 2px 8px rgba(15, 23, 42, 0.06)",
        "medium": "0 8px 24px rgba(15, 23, 42, 0.08)",
        "elevated": "0 16px 40px rgba(15, 23, 42, 0.12)",
        "card": "0 2px 8px rgba(15, 23, 42, 0.06)",
        "card-hover": "0 8px 24px rgba(15, 23, 42, 0.08)",
        "glow": "0 0 15px rgba(47, 111, 228, 0.15)",
        "glow-lg": "0 0 30px rgba(47, 111, 228, 0.25)",
        "glow-accent": "0 0 15px rgba(245, 158, 11, 0.15)",
      },
      keyframes: {
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(18px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        floating: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'glow-pulse': {
          from: { boxShadow: '0 0 5px rgba(47, 111, 228, 0.1)' },
          to: { boxShadow: '0 0 15px rgba(47, 111, 228, 0.3)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.9)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(20px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'pulse-slow': 'pulse-slow 6s ease-in-out infinite',
        'fade-up': 'fade-up 0.7s cubic-bezier(0.2, 0.8, 0.2, 1) both',
        'fade-in': 'fade-in 0.5s ease-out both',
        marquee: 'marquee 30s linear infinite',
        floating: 'floating 3s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 2s infinite alternate',
        'scale-in': 'scale-in 0.5s ease-out both',
        'slide-in-right': 'slide-in-right 0.5s ease-out both',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
